### PR TITLE
V6: Add missing migration

### PR DESCRIPTION
**Pull request by danielbeardsley**
One of the cron jobs is failing because the job we're attempting to
execute doesn't exist. It seems the Akeneo folks just forgot to include
the creation of the job instance in a migration.

Taken from https://github.com/akeneo/pim-community-dev/issues/14185#issuecomment-828188449

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA :+1: This fixes the problem in dev!
It also fixes the problem with sending email.

**Comment by danielcliu-ifixit** [comment]
CR :v:

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by danielcliu-ifixit** [comment]
oops i always forget which repos need the approval

**Comment by masonmcelvain** [comment]
Idk if this one needs approval, I just didn't see your CR

**Pull request merged**
