### PR TITLE
ProductModel Cloner: remove it

### PR DESCRIPTION
**Pull request by danielbeardsley**
We've decided we no longer needed (see @jeffsnyder). Also, it wasn't
fully updated for V4.

We're now doing everything we need via the API from the iFixit App.

Blocked on https://github.com/iFixit/ifixit/pull/35913

### CODE REVIEW

**Comment by sterlinghirsh** [comment]
CR :zap:

**Comment by sctice** [comment]
CR :flags:

**Comment by addison-grant** [comment]
Is there a good way / big need to test this?

**Comment by danielbeardsley** [comment]
Just gonna merge it. Tested with `make down && make cache && make up`  It runs fine without this (we don't use it.

QA :+1:

**Pull request merged**
