### PR TITLE
Akeneo Version 7

### PR DESCRIPTION
**Pull request by danielbeardsley**
Hot on the heels of the V6 upgrade we're trying out V7!

### CODE REVIEW

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by erinemay** [comment]
@danielbeardsley how can we test the upgrade in this repo?

**Comment by danielbeardsley** [comment]
I think @jeffsnyder and @jstephens-ifixit will be testing it (https://akeneo-next.cominor.com).

**Comment by jstephens-ifixit** [comment]
> I think @jeffsnyder and @jstephens-ifixit will be testing it

Yes, I can probably do that, but I am not super confident I know all the things to test beyond my daily activities in Akeneo. Jeff Snyder's schedule will be limited for a while (EU travel, some WFH, and then vacation). What's the time line? Should I be thinking about this right away? I have Microsoft partnership things taking my time in the very near term.

**Comment by danielbeardsley** [comment]
>  What's the time line? Should I be thinking about this right away? I have Microsoft partnership things taking my time in the very near term.

@jeffsnyder said he was interested in v7 and some of the new possibilities. I have it ready for evaluation and it seems to work fine. I don't expect there to be large changes that break any workflows. I'll ping him directly to ask if there's anything he cares to evaluate or any reason we shouldn't just go all the way.

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻

**Comment by danielbeardsley** [comment]
This worked flawlessly in dev.

In prod, one of the migrations failed to deploy.
image

I'm not 100% why it's different between prod and dev... but likely because binary logging is on in prod and not in dev (because backups). See here: https://stackoverflow.com/questions/56389698/why-super-privileges-are-disabled-when-binary-logging-option-is-on

dev_block :+1:

**Comment by danielbeardsley** [comment]
I think I found the solution. Pushed this commit: https://github.com/iFixit/server-templates/pull/4020/commits/5ac5dafb5e133f4f2e60282730a5821655d244d7

Booting a machine in prod now.

**Comment by danielbeardsley** [comment]
> Booting a machine in prod now.

It succeeded. Going through the process for real now.

**Comment by danielbeardsley** [comment]
QA :+1: 

We did the thing, this is rolled out in production.

**Comment by danielbeardsley** [comment]
un_dev_block :+1:

**Pull request merged**
