### PR TITLE
iFixit Connector: allow easily disabling

### PR DESCRIPTION
**Pull request by danielbeardsley**
We occasionally want to disable the connection that notifies our app of changes. This allows doing so by editing the config file.

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA :+1: 

I've validated that this works.

**Comment by danielbeardsley** [comment]
Pushed the config change:
image

**Comment by sterlinghirsh** [comment]
CR :zap: though it looks like we lost the return type declaration. Not going to block on it though.

**Comment by danielbeardsley** [comment]
> we lost the return type declaration

True, but I noticed that none of the call sites used the response, so I decided to drop it. Bummer that I left that out of the commit message.

**Pull request merged**
