### PR TITLE
API Retries: fix always retrying

### PR DESCRIPTION
**Pull request by danielbeardsley**
Wow. Oops. Turns out this middleware relies on us determining if we should retry or not including examining the status code. There are no docs and I then I misread the source code (or saw simplistic examples or something).

We're submitting to the Akeneo Events api on ifixit.com and it always gives back 200s, so let's consider anything non-200 as a failure.

This has been a bug since 2022-09-07:
https://github.com/iFixit/pim-community-standard/pull/20

Closes iFixit/ifixit#44723
Closes iFixit/ifixit#44627

### CODE REVIEW

**Comment by danielbeardsley** [comment]
QA :+1: 

After:
```
[2022-10-03 22:30:40] app.ERROR: Pre save: Akeneo\Pim\Enrichment\Component\Product\Model\Product [] []
[2022-10-03 22:30:40] app.ERROR: Post save: Akeneo\Pim\Enrichment\Component\Product\Model\Product [] []
[2022-10-03 22:30:40] app.ERROR: POST:admin/akeneo/skus_changed {"skus":["4600071"]} []
[2022-10-03 22:30:40] app.ERROR: Retries: 0  code: 200 [] []
```

Before:
```
[2022-10-03 22:27:34] app.ERROR: Pre save: Akeneo\Pim\Enrichment\Component\Product\Model\Product [] []                                                                                                                                        
[2022-10-03 22:27:34] app.ERROR: Post save: Akeneo\Pim\Enrichment\Component\Product\Model\Product [] []                                                                                                                                       [2022-10-03 22:27:34] app.ERROR: POST:admin/akeneo/skus_changed {"skus":["4600071"]} []                                                                                                                                           
[2022-10-03 22:27:34] app.ERROR: Retries: 0  code: 200 [] []                                                           
[2022-10-03 22:27:35] app.ERROR: Retries: 1  code: 200 [] []                                                           
[2022-10-03 22:27:37] app.ERROR: Retries: 2  code: 200 [] []                                                                                                                                                                                  
[2022-10-03 22:27:41] app.ERROR: Retries: 3  code: 200 [] [] 
```

**Comment by danielbeardsley** [comment]
Clicking save now takes ~1s as opposed to 8s.

Derp!

**Review by masonmcelvain — APPROVED** [review]
CR ✌🏻 Wow I'd expect the RetryMiddleware to handle that by default

**Comment by sterlinghirsh** [comment]
Is there a reason to retry 100 or 300 level responses? Not sure it makes a real difference, just curious.

**Comment by danielbeardsley** [comment]
> Is there a reason to retry 100 or 300 level responses? Not sure it makes a real difference, just curious.

100 means "continue" which is a seldom used HTTP quirk and 300 is redirect and Guzzle auto-follows redirects: https://guzzle3.readthedocs.io/http-client/http-redirects.html

That said, I mostly chose this for simplicity.

**Pull request merged**
